### ISSUE TITLE
Sub Directory 

### ISSUE THREAD

**Issue by Apex-94** [iotarepeat/PySync#1]
.Make a folder in Desktop example Test
2.Make another folder in Test example Test2
3.Make a file in Test folder HelloWorld.txt
4.Run server file, Run client file .
5.Client File in Test2

**Comment by iotarepeat** [comment]
OS:
Expected Behaviour: 
Please attach screenshots if possible

**Comment by Apex-94** [comment]
> Please attach screenshots if possible

Yes

**Comment by iotarepeat** [comment]
This is nested directory structure. It will always cause an infinite loop since client is inside server

Closing, because this situation will not occur during practical application.
